### ISSUE TITLE
macOS rpath issue

### ISSUE THREAD

**Issue by jminor** [OpenTimelineIO/toucan#12]
I ran the build instructions, but the resulting executables (`toucan-render` and `toucan-view`) failed to launch with this error:
```
% ./toucan-render
dyld[31171]: Library not loaded: @rpath/libavcodec.61.3.100.dylib
  Referenced from: <A5401521-E2F5-339D-88F1-929A3107421B> /Users/joshm/git/install-Release/bin/toucan-render
  Reason: no LC_RPATH's found
zsh: abort      ./toucan-render
```

I was able to fix the issue by running this:
```
% install_name_tool -add_rpath "/Users/joshm/git/install-Release/lib/" ./toucan-render
```

Now it runs and works great.

**Comment by darbyjohnston** [comment]
Hopefully this is fixed now, I enabled some RPATH options in CMake.
